name: RegrowthDiscordWebHooks
version: ${project.version}
main: org.lushplugins.regrowthdiscordwebhooks.RegrowthDiscordWebHooks
api-version: '1.21'
softdepend:
  - PlaceholderAPI
github-repo: RegrowthMC/RegrowthDiscordWebhooks